name: Node.js CI

on:
  push:
    branches: [ "main" ]


jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.12.2]
    env:
       NEXT_APP: ${{secrets.NEXT_APP}}   

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
  
